<a href="https://colab.research.google.com/github/thammagig/redrose/blob/master/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# create one-dimensional array
from numpy import array

In [4]:
# list of data
data = [55, 44,33,22,11]
print(data)
print(type(data))

[55, 44, 33, 22, 11]
<class 'list'>


In [5]:
data = array(data)
print(data)
print(type(data))

[55 44 33 22 11]
<class 'numpy.ndarray'>


In [0]:
data2 = [[11,22],
         [33,44],
         [55,66]]

In [7]:
data2 = array(data2)
print(data2)
print(type(data2))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


In [8]:
data2[0]

array([11, 22])

In [9]:
data2[0][0]

11

In [10]:
data2[-1]

array([55, 66])

In [14]:
data2[:,1]

array([22, 44, 66])

In [0]:
data = array([[11,22,33],
             [44,55,66],
             [77,88,99]])

In [18]:
X, y = data[:,:-1] , data[:,-1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


It is common to split a loaded dataset into separate train and test sets. This is a splitting of rows where some portion will be used to train the model and the remaining portion will be used to estimate the skill of the trained model. This would involve slicing all columns by specifying : in the second dimension index. The training dataset would be all rows from the beginning to the split point.

train = data[:split, :]

test = data[split:, :]

In [19]:
# split train and test data
from numpy import array
# define array
data = array([
  [11, 22, 33],
  [44, 55, 66],
  [77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)


[[11 22 33]
 [44 55 66]]
[[77 88 99]]


In [21]:
# shape of one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55]) 
print(data.shape)

(5,)


In [23]:
# shape of a two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data) 
print(data.shape)

(3, 2)


In [25]:
# row and column shape of two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
        [33, 44],
[55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0]) 
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


In [28]:

# reshape 1D array to 2D
from numpy import array
# define array
data = array([11, 22, 33, 44, 55]) 
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1)) 
print(data.shape)

(5,)
(5, 1)


In [29]:
data

array([[11],
       [22],
       [33],
       [44],
       [55]])

In [30]:
# reshape 2D array to 3D
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1)) 
print(data.shape)

(3, 2)
(3, 2, 1)
